- name: Install Packages 1
  become: true
  apt:
    name: ["build-essential", "cmake", "apt-transport-https", "ca-certificates", "software-properties-common"]
  tags:
    - install
    - languages
- name: Install Packages 2
  become: true
  apt:
    name: ["golang", "python3-pip", "virtualenv", "python3-setuptools"]
  tags:
    - install
    - languages
- name: Install rustup
  shell: curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh -s -- -y
  tags:
    - install
    - languages
- name: Source cargo env
  shell: source "{{ lookup('env', 'HOME') }}"/.cargo/env
  tags:
    - install
    - languages
- name: Install rust-analyzer
  shell: rustup component add rust-analyzer-preview
  tags:
    - install
    - languages
