- name: Ensure .ssh directory exists.
  ansible.builtin.file:
    dest: "{{ dest_dir }}"
    mode: "0700"
    state: directory
  tags:
    - dotfiles
    - ssh
- name: Install ssh key
  ansible.builtin.copy:
    src: "{{ source_dir }}id_rsa"
    dest: "{{ dest_dir }}id_rsa"
    mode: "0600"
  tags:
    - dotfiles
    - ssh
- name: Install nuc key
  ansible.builtin.copy:
    src: "{{ source_dir }}id_nuc"
    dest: "{{ dest_dir }}id_nuc"
    mode: "0600"
  tags:
    - dotfiles
    - ssh
- name: Install nuc pub
  ansible.builtin.copy:
    src: "{{ source_dir }}id_nuc.pub"
    dest: "{{ dest_dir }}id_nuc.pub"
    mode: "0600"
  tags:
    - dotfiles
    - ssh
- name: Install config
  ansible.builtin.copy:
    src: "{{ source_dir }}config"
    dest: "{{ dest_dir }}config"
    mode: "0600"
  tags:
    - dotfiles
    - ssh
- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  tags:
    - dotfiles
    - ssh
