- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  tags:
    - zsh
    - install
- name: Change shell
  shell: chsh -s `which zsh`
  tags:
    - zsh
    - install
- name: Install oh-my-zsh
  shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  tags:
    - zsh
    - install
- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1
  tags:
    - zsh
    - install